# Réduit la mémoire maximale utilisée par Gradle à 1,5 Go (au lieu de 8 Go)
org.gradle.jvmargs=-Xmx1536M -Dfile.encoding=UTF-8

# Désactive le mode daemon pour éviter les crashs liés à la RAM limitée
org.gradle.daemon=false

# Active le mode de compilation parallèle
org.gradle.parallel=true

# Réduit la taille du cache pour éviter les surcharges mémoire
org.gradle.caching=true

# Active le support de configuration à la demande
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true

org.gradle.jvmargs=-Xmx1024M
